# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AePA7JGPoIMuqmYhHSm6Hn6sUl8UsU-l

#Import Libraries
"""

# Import Pandas Library
import pandas as pd

# Load the HR Analytics Dataset
df = pd.read_csv("HR_Analytics.csv")

# Display first 5 rows
df.head()

"""The dataset contains employee-related information such as employee ID, age, department, job role, salary, work experience, satisfaction levels, overtime status, and employee attrition.

#Task A2: Inspect the Dataset
"""

# First 10 rows
print(df.head(10))

# Last 10 rows
print(df.tail(10))

# Number of rows and columns
print(df.shape)

# Column names
print(df.columns)

# Data types
print(df.dtypes)

# Basic information
df.info()

"""Dataset inspection helps understand the structure and quality of the data. The first and last records provide an overview of the dataset, while the shape indicates the number of observations and features. Column names and data types help identify categorical and numerical variables, and the info() function highlights missing values and memory usage.

#Part B: Data Quality Check

Task B1: Check Missing Values

Missing Value Analysis
"""

# Check missing values
missing_values = df.isnull().sum()

print(missing_values)

"""Missing Value Percentage"""

missing_percentage = (df.isnull().sum()/len(df))*100

print(missing_percentage)

"""According to your dataset:

Most columns have no missing values.
Only YearsWithCurrManager contains missing values.
Total missing values = 57.



The HR Analytics dataset contains very few missing values. Only the YearsWithCurrManager feature has 57 missing observations, while all other variables are complete.

#Task B2: Duplicate Records

Duplicate Analysis
"""

duplicate_count = df.duplicated().sum()

print("Duplicate rows :", duplicate_count)

"""#Task B3: Invalid or Unusual Values

1 Age Validation
"""

invalid_age = df[(df["Age"]<18) | (df["Age"]>60)]

print(invalid_age)

"""2. Monthly Income Validation"""

invalid_income = df[df["MonthlyIncome"]<=0]

print(invalid_income)

"""3. Total Working Years Validation"""

invalid_work = df[df["TotalWorkingYears"]<0]

print(invalid_work)

"""The HR Analytics dataset was examined for data quality issues. Missing values were identified only in the YearsWithCurrManager column. Validation checks for employee age, monthly income, and total working years returned empty DataFrames, indicating that no unrealistic or invalid values exist in these variables. Overall, the dataset demonstrates good data quality and requires minimal cleaning before further analysis.

#Part C: Data Cleaning

Part C: Data Cleaning
"""

# Fill missing values with median

df["YearsWithCurrManager"] = df["YearsWithCurrManager"].fillna(
    df["YearsWithCurrManager"].median()
)

# Check missing values again

print(df.isnull().sum())

"""After applying median imputation, the dataset contains no missing values.

#Task C2: Duplicate Removal
"""

# Check duplicates

print(df.duplicated().sum())

# Remove duplicates

df = df.drop_duplicates()

# Verify

print(df.duplicated().sum())

"""#Task C3: Text Standardization"""

text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip().str.title()

df.head()

"""#Task C4: Data Type Conversion"""

print(df.dtypes)

"""#Task C5: Rename Columns"""

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
)

print(df.columns)

"""#Part D: Exploratory Data Analysis (EDA)

Task D1: Summary Statistics
"""

df.describe()

# Categorical Summary
df.describe(include="object")

"""Task D2: Value Counts

1.Attrition
"""

df["attrition"].value_counts()

"""2.Department"""

df["department"].value_counts()

"""Gender"""

df["gender"].value_counts()

"""#Task D3: Filtering

Filter 1: Employees with Attrition
"""

attrition_emp = df[df["attrition"]=="Yes"]

attrition_emp.head()

"""Filter 2: Employees Working Overtime"""

overtime_emp = df[df["overtime"]=="Yes"]

overtime_emp.head()

"""Filter 3: High Income Employees"""

high_income = df[df["monthlyincome"]>10000]

high_income.head()

"""Filter 4: Employees Above Age 40"""

age_above_40 = df[df["age"]>40]

age_above_40.head()

"""Filter 5: Married Employees"""

married_emp = df[df["maritalstatus"]=="Married"]

married_emp.head()

"""Task D4: Sorting"""

top_income = df.sort_values(
    by="monthlyincome",
    ascending=False
)

top_income.head(10)

"""Task D5: Column Selection"""

selected_df = df[
    [
        "empid",
        "age",
        "department",
        "jobrole",
        "monthlyincome",
        "attrition"
    ]
]

selected_df.head()

"""#Part E: Grouping and Aggregation

Task E1: Single-Level Grouping

Department-wise Salary Analysis
"""

department_summary = df.groupby("department").agg(
    employee_count=("empid","count"),
    total_salary=("monthlyincome","sum"),
    average_salary=("monthlyincome","mean"),
    minimum_salary=("monthlyincome","min"),
    maximum_salary=("monthlyincome","max")
).reset_index()

department_summary

"""#Task E2: Multi-Level Grouping

Task E2: Department and Attrition Analysis
"""

department_attrition = df.groupby(
    ["department","attrition"]
).agg(
    employee_count=("empid","count"),
    average_salary=("monthlyincome","mean"),
    average_experience=("totalworkingyears","mean")
).reset_index()

department_attrition

"""#Task E3: Top Groups

Task E3: Top Salary Departments
"""

top_departments = department_summary.sort_values(
    by="total_salary",
    ascending=False
).head(10)

top_departments["Rank"] = range(1, len(top_departments)+1)

top_departments

"""#Part F: Feature Engineering

Task F1: Employee Experience Category
"""

def experience_category(x):
    if x <= 5:
        return "Beginner"
    elif x <= 10:
        return "Intermediate"
    elif x <= 20:
        return "Experienced"
    else:
        return "Expert"

df["experience_category"] = df["totalworkingyears"].apply(experience_category)

df[["totalworkingyears","experience_category"]].head()

"""Task F2: Salary Category"""

def income_category(x):
    if x < 5000:
        return "Low"
    elif x < 10000:
        return "Medium"
    else:
        return "High"

df["income_category"] = df["monthlyincome"].apply(income_category)

df[["monthlyincome","income_category"]].head()

"""Task F3: Promotion Status"""

df["promotion_status"] = df["yearssincelastpromotion"].apply(
    lambda x: "Recently Promoted" if x <= 2 else "Not Recently Promoted"
)

df[["yearssincelastpromotion","promotion_status"]].head()

"""Overtime Category"""

df["overtime_status"] = df["overtime"].apply(
    lambda x: "Extra Hours" if x=="Yes" else "Normal Hours"
)

df[["overtime","overtime_status"]].head()

"""#Part G: Visualization

Chart 1: Department-wise Employee Count
"""

plt.figure(figsize=(8,5))

plt.hist(df["monthlyincome"], bins=30)

plt.title("Monthly Income Distribution")
plt.xlabel("Monthly Income")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""Chart 2: Monthly Income Distribution"""

plt.figure(figsize=(8,5))

plt.hist(
    df["monthlyincome"],
    bins=30,
    color="purple",
    edgecolor="black"
)

plt.title("Monthly Income Distribution",fontsize=14)
plt.xlabel("Monthly Income")
plt.ylabel("Frequency")

plt.grid(alpha=0.3)

plt.show()

"""Employee Distribution by Age Group"""

age_attrition = df.groupby("agegroup").agg(
    employee_count=("empid","count")
).reset_index()

plt.figure(figsize=(8,5))

plt.plot(
    age_attrition["agegroup"],
    age_attrition["employee_count"],
    marker="o",
    color="green",
    linewidth=3,
    markersize=8
)

plt.title("Employee Distribution by Age Group",fontsize=14)
plt.xlabel("Age Group")
plt.ylabel("Employee Count")

plt.grid(alpha=0.3)

plt.show()

"""Salary Distribution by Attrition"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="attrition",
    y="monthlyincome",
    palette="Set2"
)

plt.title("Salary Distribution by Attrition",fontsize=14)

plt.show()

"""#Part H: Correlation Analysis

Task H1: Calculate Correlation Matrix
"""

# Select numerical columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Correlation matrix
correlation_matrix = numeric_df.corr()

correlation_matrix

"""Task H2: Correlation Heatmap"""

plt.figure(figsize=(16,10))

sns.heatmap(
    correlation_matrix,
    cmap="coolwarm",
    annot=False,
    linewidths=0.5
)

plt.title("Correlation Heatmap", fontsize=16)

plt.show()

"""Task H3: Find Highly Correlated Variables"""

corr_pairs = correlation_matrix.unstack()

corr_pairs = corr_pairs.sort_values(ascending=False)

corr_pairs.head(20)

"""Task H4: Business Interpretation

Observation

The correlation analysis was performed on numerical variables to understand relationships among employee attributes. The heatmap provides a visual representation of these relationships and helps identify variables that move together.

HR Insights

Insight 1

Employee experience-related variables such as Total Working Years, Years at Company, and Years in Current Role tend to have positive relationships.

Insight 2

Salary-related variables generally increase with employee experience and job level.

Insight 3

Correlation analysis helps HR professionals identify important factors associated with employee growth and career progression.

#Part I: Data Export and Reporting

Part I: Data Export and Reporting
"""

# Export cleaned dataset

df.to_csv("HR_Analytics_Cleaned.csv", index=False)

print("Cleaned dataset exported successfully.")

"""Task I2: Export Department Summary"""

department_summary.to_csv(
    "Department_Summary.csv",
    index=False
)

print("Department summary exported.")

"""Task I3: Export Job Role Summary"""

jobrole_summary = df.groupby("jobrole").agg(
    employee_count=("empid", "count"),
    average_salary=("monthlyincome", "mean")
).reset_index()

jobrole_summary

jobrole_summary.to_csv(
    "JobRole_Summary.csv",
    index=False
)

print("Job role summary exported successfully!")

""" Task I4: Export Attrition Summary"""

attrition_summary = df.groupby("attrition").agg(
    employee_count=("empid", "count"),
    average_income=("monthlyincome", "mean"),
    average_age=("age", "mean")
).reset_index()

attrition_summary

attrition_summary.to_csv(
    "Attrition_Summary.csv",
    index=False
)

print("Attrition summary exported successfully!")

"""Task I5: Save Top Salary Departments"""

department_summary = df.groupby("department").agg(
    employee_count=("empid","count"),
    total_salary=("monthlyincome","sum"),
    average_salary=("monthlyincome","mean")
).reset_index()

department_summary.to_csv(
    "Department_Summary.csv",
    index=False
)

top_departments.to_csv(
    "Top_Departments.csv",
    index=False
)

print("Top departments exported.")

"""#Part J: Business Insights and Recommendations

#Business Insights from HR Analytics Dataset
Insight 1: Employee Attrition

The dataset contains employees who have left the organization as well as those who stayed. Understanding attrition patterns helps HR improve employee retention strategies.

Insight 2: Department Distribution

Employee distribution varies across departments, indicating different workforce requirements and operational needs.

Insight 3: Salary Structure

Monthly income differs across employees and job roles, reflecting varying responsibilities and experience levels.

Insight 4: Employee Experience

Employees have different levels of work experience, ranging from beginners to experienced professionals.

Insight 5: Overtime

Overtime information provides useful insights into employee workload and potential work-life balance issues.

Insight 6: Promotion Patterns

Years since last promotion can help identify employees who may require career development opportunities.

Insight 7: Workforce Demographics

Employee age groups and gender distribution provide valuable demographic information for HR planning.

Insight 8: Data Quality

The dataset is well-structured with minimal missing values and very few data quality issues, making it reliable for analysis.

#Task J2: Business Recommendations

HR Recommendations
Recommendation 1

Regularly monitor employee attrition and conduct exit interviews to identify common reasons for turnover.

Recommendation 2

Develop employee retention programs for departments experiencing higher attrition.

Recommendation 3

Review overtime policies to ensure employees maintain a healthy work-life balance.

Recommendation 4

Provide regular training and career development opportunities to improve employee engagement.

Recommendation 5

Establish transparent promotion policies to motivate employees and encourage long-term commitment.

Recommendation 6

Periodically review salary structures to maintain competitive compensation.

Recommendation 7

Use workforce demographic information for effective succession planning and talent management.

Recommendation 8

Continue maintaining high data quality standards to support accurate HR decision-making.
"""



