import os
import joblib
import pandas as pd
from flask import Flask, render_template, request, send_from_directory, url_for

app = Flask(__name__)
MODEL_PATH = os.path.join(os.path.dirname(__file__), '..', 'models', 'best_model.joblib')
MODELS_DIR = os.path.join(os.path.dirname(__file__), '..', 'models')

model = None

def load_model():
    global model
    if os.path.exists(MODEL_PATH):
        model = joblib.load(MODEL_PATH)
    else:
        model = None


load_model()

def prepare_input(data: dict) -> pd.DataFrame:
    df = pd.DataFrame([data])
    df = df[['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']]
    return df


@app.route('/', methods=['GET', 'POST'])
def index():
    prediction = None
    probability = None
    eval_results = None
    images = []
    model_error = None
    if request.method == 'POST':
        user_data = {
            'CreditScore': int(request.form['CreditScore']),
            'Geography': request.form['Geography'],
            'Gender': request.form['Gender'],
            'Age': int(request.form['Age']),
            'Tenure': int(request.form['Tenure']),
            'Balance': float(request.form['Balance']),
            'NumOfProducts': int(request.form['NumOfProducts']),
            'HasCrCard': int(request.form['HasCrCard']),
            'IsActiveMember': int(request.form['IsActiveMember']),
            'EstimatedSalary': float(request.form['EstimatedSalary']),
        }

        input_df = prepare_input(user_data)
        if model is not None:
            prediction = model.predict(input_df)[0]
            probability = model.predict_proba(input_df)[0][1]
        else:
            model_error = "Model file not found. Run the training script first."
    # Load evaluation results CSV if available
    eval_csv = os.path.join(MODELS_DIR, 'model_evaluation_results.csv')
    if os.path.exists(eval_csv):
        try:
            eval_results = pd.read_csv(eval_csv).to_dict(orient='records')
        except Exception:
            eval_results = None

    # List model images (feature importance, ROC curves) from models dir
    if os.path.isdir(MODELS_DIR):
        for fname in os.listdir(MODELS_DIR):
            if fname.lower().endswith(('.png', '.jpg', '.jpeg')):
                # build image URL directly to avoid url_for BuildError during reloader startup
                images.append(f'/images/{fname}')

    return render_template(
        'index.html',
        prediction=prediction,
        probability=probability,
        eval_results=eval_results,
        images=images,
        model_error=model_error,
    )
@app.route('/images/<path:filename>')
def model_image(filename):
    # Serve images generated by training (stored in src/models)
    return send_from_directory(MODELS_DIR, filename)


if __name__ == '__main__':
    load_model()
    app.run(debug=True)
